name: CI

on:
  push:
    branches:
      - master
  pull_request:
    # run in all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
        # Will add next jobs as per code requirements
